# Pair notebooks in subfolders of 'notebooks' to scripts in subfolders of 'scripts'
# so that running
# rm scripts/* && jupytext --sync notebooks/*
# generates files in scripts/ for each notebook
[formats]
"notebooks/" = "ipynb"
"scripts/" = "py:percent"
